org: onerep
app: serverless-tdc
service: workshop

provider:
  name: aws
  stage: production
  region: sa-east-1
  runtime: nodejs22.x
  versionFunctions: false
  memorySize: 512
  timeout: 10
  logRetentionInDays: 3

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'

functions:
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: users
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true

  getAllUsers:
    handler: handler.getAllUsers
    events:
      - http:
          path: users
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true

  getUser:
    handler: handler.getUser
    events:
      - http:
          path: users/{id}
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true

  updateUser:
    handler: handler.updateUser
    events:
      - http:
          path: users/{id}
          method: put
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true

  removeUser:
    handler: handler.removeUser
    events:
      - http:
          path: users/{id}
          method: delete
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true


